# Generated by Django 4.1.6 on 2023-02-03 03:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('position', models.SmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Email could include "0-9,a-z,A-Z,_,-,." only', regex='^[0-9a-zA-z]+([-\\.]?[0-9a-zA-z_])*@[0-9a-zA-z]+(\\.?[0-9a-zA-z])*$')])),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone in format xxx xxx xxxx', regex='^(\\d{3}[- ]?){2}\\d{4}$')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number_people', models.PositiveSmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=250)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date', '-time', '-is_processed'),
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('ingredients', models.TextField(max_length=200)),
                ('is_visible', models.BooleanField(default=True)),
                ('position', models.SmallIntegerField()),
                ('photo', models.ImageField(upload_to=main_page.models.Dish.get_file_name)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.category')),
            ],
            options={
                'ordering': ('position', 'price'),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
